spring.application.name=cognition_crm_Institute
spring.datasource.url=jdbc:mysql://localhost:3306/cognition_crm2
spring.datasource.username=root
spring.datasource.password=savita

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false


server.port=8080
